secrets:
    data:
        - name: ENC[AES256_GCM,data:mnkFng4onyWqbrhQoVbbpJ1Zih8=,iv:WQgNOuSAAcu+eFAp/0f9KxTzHrxeL5IPQOo+HX7qfow=,tag:3eNSO2kTZqes4rP75EWXgw==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:CRBEXus7828=,iv:FoVkpkwgMzL92dueIPt4FtkkMjAGz59xKGxIwe3HUaQ=,tag:2uYTwatXrDrpwLi5lOyPow==,type:str]
            admin-password: ENC[AES256_GCM,data:z3OQZGiiBo0=,iv:gF9myoJQEn9gQnjSG5J2ZIgQOt26QJaENU9PigWmgUY=,tag:Eoz1g+iBdJEtNxnrpmqfRQ==,type:str]
        - name: ENC[AES256_GCM,data:i50l2g8QJLB9D8iqJB+8glS+6A==,iv:w/XVM9lFvV3yi4G/guG1vQDig56XoEMKxv5oqirokh4=,tag:IoKmXC1MIwZkWzvhuWqSFQ==,type:str]
          stringData:
            .htpasswd: ENC[AES256_GCM,data:rv9wvcuu1f9cz0PTZKf8LUHpPaWctU4uiGrbEm5c1x8bSPL75VtiTHOINyq/CCrnIXjZzQ==,iv:8Yo4Xzp6cI/UOt4LdNSbwlr7OS2KiEVnHPUigYR4WdA=,tag:vQzNuAdfAQhC78HbFRVBBQ==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:+VR1xQ==,iv:+IY3ax3uyrQ5MRdanBd7UgSSIjQR447iLWObtCSUBS4=,tag:jAXpdQVFSoaV/vpWnDt2Tw==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:pKJgDQ==,iv:WWLjyw59x54bicxRuE0nNVCqZFeH8DsCXpTxMKOsCrc=,tag:EbhvUXJ4u9ohN7VX7iqYbA==,type:str]
#ENC[AES256_GCM,data:MPXOylvT,iv:WO5Ar4aZ7w5/IM9cMxnDG8jGp6bKsAlesvYDioMWFa0=,tag:nX06YN+MXailaap7nbiWBw==,type:comment]
#ENC[AES256_GCM,data:jAGtcBxldHgjZoY=,iv:iPuiH5kFFUC84ybdxWr6l6BI+HGCclkuN1HRTnXcPj4=,tag:K35i7XcuC0px+e8xEr0gEA==,type:comment]
#ENC[AES256_GCM,data:mKIlTFYMfw7k5EAoFaSk,iv:kGfjtuOyORszAjArqSGP0zCzvl8sjFQqRVF9Jf1+QCk=,tag:SZEJ7A9pp3EyHSSK2NoZRA==,type:comment]
#ENC[AES256_GCM,data:wC7pnkebgTYl1KjjXunkTfFRAMs=,iv:sZ/Wjdcz80dsHmynA5xhjJLelGF4RFcO5aOjMM6aXxI=,tag:tksvZBBi2c66W71LCdGffg==,type:comment]
#ENC[AES256_GCM,data:CCbl6JjORNG0Etru2lsE2raQy6+/FkcUXKY6XQ2WXs+/i2xzR17zwqmzY/XA7nW+WyMaDLpbbKlfJ/8p7w==,iv:qfShatdVO05TaJxmIKzzMIo6ihj1lLqwxF40RPUKMNU=,tag:NNWGaGqnXzAWuuK45nTJuw==,type:comment]
#ENC[AES256_GCM,data:YtJDlqAyUHxY,iv:ovuWnkVvSdyNB5yBqJKDWYZJJ0+mPKLu0MKrRJtNtyA=,tag:VY5doW3R6sLArFT7U5XmwQ==,type:comment]
#ENC[AES256_GCM,data:2DSenzowijwV6s5g+Zbb,iv:DM1OGp/Y75VYgJRTu9ikcWrPkm6GGDPUmFh81mT0fWg=,tag:0pOPtMyLMeNKjhigvDQu2Q==,type:comment]
#ENC[AES256_GCM,data:bRHRnUs8PCPxCUeDDGSNq8Jju7dGXw==,iv:l9kLWW2STCrUp/aS6HSAXpoyKKDjAvlKdnFeYj4FrXY=,tag:yp40naH1lmzfYzNo7Kl+wg==,type:comment]
#ENC[AES256_GCM,data:OqrpAyBvOdrIFXrUEuv4bTz1o/4=,iv:6L7s/vF+ys0rKRLma2qFtrpC2HgT5lma9yVdcRK1Hos=,tag:qphVPxDGMyanlSvbzTQvNA==,type:comment]
#ENC[AES256_GCM,data:kf2kVq3s0JdYfiwReVy/sPhdtA==,iv:50ZG04j4bIq23qgHH0JIn6H4AfirO996gusaGeixDqk=,tag:jsydXl5LxPbqwtpNRyTSJA==,type:comment]
#ENC[AES256_GCM,data:JfXakoSfIn1Y65XCcoFRPq/6WlZC,iv:Yw/BDhBAbl8oTtaBSNYB6hauArUp1j7OAxbbwNoTeTk=,tag:/qkSg7b0/N6YSn4FBsbkwQ==,type:comment]
#ENC[AES256_GCM,data:TQDGPewI9wAPyJ+SXWdlEQdMUkTz,iv:8x+hgFLq8twX3jq+E39N4IE0fJJ5rxIXWY9juOKsq94=,tag:MO3bmYcW2VTX4yFMkWppcA==,type:comment]
#ENC[AES256_GCM,data:QKbiwAZ00VBLasOVVTm/TKkppGU7g3NKOoM=,iv:vnXxd/SRTeMJ2Y3LsC4kD7KjmtmXr6umJtHQZ42Xf9c=,tag:G/n0ifnORnUqDL6EMOUczA==,type:comment]
#ENC[AES256_GCM,data:YHISQ5bfC7A2bGaiUokKftnwxtcoEki5,iv:wz+rcrQ2xPA77qVgyuKW7pHaVPm4BItJszW8PPEP+o0=,tag:QP+y04qzhQgAszv7wwpRTw==,type:comment]
#ENC[AES256_GCM,data:cSyze60DVUE7alUS3NzbcgzvSc3JyV+SziLh3t8zDAjEXlrhWGSqP8U4dqKsSrucQsFOcoiBM7DY45nLAywDE2liyd9Sx0xgFcZgl2zP8g==,iv:mc4Rp8Iuarf5tx9Klus13wY8YSqubVqZYXmQkCmS/N4=,tag:3HWaRn7DCqihbwcunQlvcw==,type:comment]
#ENC[AES256_GCM,data:7W5brUkC204jJNHSi4hbPaQUPPkmWqtfPq4=,iv:NvaBnUepjoIqtYOVMd3Zkc0MlK0RAJiul+rwjAsJkgY=,tag:Th+fGfkNMK7nkTw2Fh7A4A==,type:comment]
#ENC[AES256_GCM,data:yufE/AbcktC8HiHKlcB+6MHiFHZ77hIL2ikGrPxS,iv:aVmXHCnXhyMU0HGLnavBwqcuBRTRWqGCSZF2CdTZKi8=,tag:nGoXKBW757GDU1vH8dU0qg==,type:comment]
#ENC[AES256_GCM,data:7HU0gMiZchM+RD3ckMwLjdQKqY6SFPw4wU6IOAd64uxcSA==,iv:9WJ0Jk5G3NFS6QMSAcdtNmFZdjr9g61pDPvojsh1Wxw=,tag:xOJ96gmXfHEMELaDbJGCqQ==,type:comment]
#ENC[AES256_GCM,data:rOYahqgwH1enGKJoI2YYsUDF+yY=,iv:rH26FDDt7HbySlRG4jE/iCnCjzLm1LAxsajktGGtJoQ=,tag:6iHpwSJTW8kuXOi3qks1Zw==,type:comment]
#ENC[AES256_GCM,data:jrcbbzbh9VDYxnchdIchGKxB1ZGHm7g+/z1L,iv:O/hkKFkGGN4Tj7QgocxDG3mUyzTWammvQskucu6Efp0=,tag:oY2f0RRNUVUCww1M5cOA3g==,type:comment]
#ENC[AES256_GCM,data:2Rsp2PYVgTFXUY3vxvvUu8Fb7DMxLCLrrtbDo6BPHAD8UAkAJIg/P3wP2A==,iv:gpCr3eBG+brg580LYfe8Fftp9snzPMIbSR8FK4g3L2c=,tag:YMmasVjvVlgTyJHE/vNZeg==,type:comment]
#ENC[AES256_GCM,data:MW5lIoat/0BBW6ommsfg755wU5WXNV95B4Q=,iv:rjwj8XO7rN0oNnvxxMF+IVC9Ok26Ng+VoOZ/nAeDj0w=,tag:9xeKAUY3hYhv48NFiEsUOg==,type:comment]
#ENC[AES256_GCM,data:fXrknlXZrKWCgZE/4aItsuc7kE1Q/7zCN6MCDLG6S70dCh9SBbdrnuMe8Q4NVWjCZZV39OohQSNIrabNTW1tUMip6I8a,iv:RtQX3b2N3kP8OcS6jWJR821bTDYWr1eBP0yhmQoa3es=,tag:uzPXWXK1z12lY4+MxhqPOQ==,type:comment]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdU8rNitFSDY0TnN6REVk
            MTFHdTk1YmFGWTZqY3NNblUzYTcyOGNvN1FrClhpNjUvaE51SE9XTGlwU0dlMUR3
            Y0xSNlNjTWNSc3lCWDdicVRHQ1J4Wm8KLS0tIDJLUzZkTkdHVG1la2dRdlBobEp1
            TWRlY2lVUXZEZ1RqVkY0RlhtVXZwSWsKiWk6mdPQGhlstkEiU8G7Z6KzmkzFTCFx
            zUlMriN22QRGoMC4B5EVC3dJLUhy7ji/SYMwkZLFm6OujK9I0K21Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T08:32:08Z"
    mac: ENC[AES256_GCM,data:vWnCG2IKCI3VQ05JoC6SyH5eEe7+/+tti5R7x39hLC7rcp+uxOyTaeJ5B/WtxMAk4fJ4iywI71ZYGOgYGxINsa8SzhxjmyeGcCX0h6yXrc4WEUtm3n0zUVgkbxB2EavwDGPP73pLVbyQOKD7NtsAXtXOU25M116+FJ6yZmPk7II=,iv:BGt5Fl1GC8o8KwjxM33dHqK44l3LF/jNsiTgemPZKoo=,tag:l9a3VL/neze+s6V/2N4i/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
