secrets:
    data:
        - name: ENC[AES256_GCM,data:acYcBkF1IuxomgaLP7Y+j0gueUU=,iv:DoMS9s8XgsIdVKSASlOAFatQdtr07vB2/gdPu+wPwkE=,tag:GETOiVTIIQCGLQJRMF8ZXw==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:CuoEbWFK8Yw=,iv:A3LdLCaIn6AXRiihIa/KpkouyqAHO0+6xVWr/Kc8Nyw=,tag:G6OMrnSOw00/mEl5HgZXlA==,type:str]
            admin-password: ENC[AES256_GCM,data:XZGrAdfLy9Q=,iv:absibHB8vgW7JzzjR6O+bDw0tPWCK1g2EQplJwVkcCs=,tag:boqNuu5fKSJhXl5xoi68CA==,type:str]
        - name: ENC[AES256_GCM,data:JUIYn3non9fG8sm4O9c6fqkliQ==,iv:qq/8wlh3MfgdUuxdsO1CcUeH+79XRtrISKcd+IdlXU4=,tag:K3qR/EBrHxk7tOMlywYg4g==,type:str]
          stringData:
            .htpasswd: ENC[AES256_GCM,data:b6w4X6ZKpm8aaOhq85JWd6rfjKFDzXmRrKziyzfwLpT6kGs+vh83aJbq3xyjXU16y9WHig==,iv:oELtWqR30eMCEdd4+yeWi1yD9xl+uLKgHqXlOa9SUvc=,tag:jKrTnNcOVOx6Az4GnijI4g==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:7QYKsQ==,iv:n7dOflyII05165+FopMkMe8K2pXzgGl4kbtnUgubZw4=,tag:Sdlxv/kBagCFH7IbYsA+Pg==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:sLTOhQ==,iv:uWVLJJEEgIk7Cn0gkZtZtYxNycAAh+dQukl3g0VKS9A=,tag:uwVuqub+4ykn6aTwXhUQDA==,type:str]
#ENC[AES256_GCM,data:3YG8M/a5,iv:BEmGbaTZIRs/CGQXrLGolh7xfzhZ6P0Vbq95lId+HY8=,tag:ESboUff/21zE7iJ612LN2g==,type:comment]
#ENC[AES256_GCM,data:3m5wx5ZDHEGP9z8=,iv:jok5DA5BXqjahHC2QPgYoEYNA89SYbPHna5OloZ8pWo=,tag:gB/1CrQBLD09OMH+RuBzKw==,type:comment]
#ENC[AES256_GCM,data:jfLObuMtmWetiKZ07Fna,iv:WsfAsKexCjliKVtEHtjeZatlzaXiB8HwaDDkrKYKHBY=,tag:bGhpzEvh0U8LuyIv+d89qw==,type:comment]
#ENC[AES256_GCM,data:8CAqSIuh8NExK9+OIsb0drSqxk4=,iv:QUelAE91wLUxLtsDFamFJIUhJk0kLYw3LUu2WW/JaJo=,tag:tEyQwQZ/ZJOK2KRWtBBYdA==,type:comment]
#ENC[AES256_GCM,data:Ddee/cHFcJlJ6folvq4/xOD3ml+fkSQjRYmZg8m9B6hImIvxnmkvOz3MDqTTSgwBem6PNpc7S//v353mmA==,iv:E3/3TNKxLhsy6dYRMwr982Qg6lDi2xPBEpo2qGimnwo=,tag:bv1dnRGIURlMF/64TBTXbA==,type:comment]
grafana:
    datasources:
        datasources.yaml:
            apiVersion: ENC[AES256_GCM,data:9A==,iv:aWGS2IbQLY2MBf0SCVft8uB4HsV7JY/CprFNafIsvgg=,tag:hMMUb2i0lDyoF17U03Xm0w==,type:int]
            datasources:
                - name: ENC[AES256_GCM,data:Mf6Zmg==,iv:s11PJk1F3sINVPg+2+zEmU7np07C6vDojhXOphbSNbk=,tag:ZQ0Emd9do6c4hvAwqiPbIQ==,type:str]
                  type: ENC[AES256_GCM,data:oGmhiA==,iv:rREBhSAZDWxs88I/IkL/PE28Png4MaX4qMgDDFGrl2Y=,tag:WF76XEj/9cc0FypMTRZQjQ==,type:str]
                  isDefault: ENC[AES256_GCM,data:Th8pPg==,iv:c9EmCWfj8gKEX9/oixPjqtR2OTU5x/BEPF1Ze2WrmfM=,tag:P2zVibO8cRNBbPlIzoXu1w==,type:bool]
                  access: ENC[AES256_GCM,data:d0TE4j4=,iv:kNMbSrMXozb8pAKbXypK1Q23zGHTSez8oP1pAVhrkmE=,tag:mCpI67Qbl+QiDE9dY+bTqw==,type:str]
                  url: ENC[AES256_GCM,data:YO/yo9AtKTEaL3wvjhzNUkR0TO+sbDYriPAGeGVpbDC/qEuJ6SPZqxTnJ2JN64FcjC4pE8aAHHJj+mUCtF9J,iv:E4GopDcH0t15YAMRGJC90ZyFNbmlGle4fU4Mx8DHws4=,tag:/8lln5roJ29Oj80VZahE9Q==,type:str]
                  basicAuth: ENC[AES256_GCM,data:TQwxIQ==,iv:QAmEvAEQr6jrro0Wp2EEYlizLAPoluotiEFmXofErE0=,tag:YyBYiApulwB4CLRbaB+fow==,type:bool]
                  basicAuthUser: ENC[AES256_GCM,data:Wk/wkg==,iv:EnrQ1VB0Ixzsa3u4c0/Syc5HJBewGpZuk+AhFFg2zFg=,tag:tsKNsFt7yRSWCV6s+1S6lw==,type:str]
                  basicAuthPassword: ENC[AES256_GCM,data:evY3xQ==,iv:UjMR2dryKR0MnjNh60MMEU40mcn3q1N/jwM9lWTUsdA=,tag:RWMuNGExJsLPj3+PIUJYeQ==,type:str]
                  jsonData:
                    maxLines: ENC[AES256_GCM,data:rnWaag==,iv:2xAUhG3eu9zb/pgQtY+TVTLGnul+CRzsT+SdG5sLjAw=,tag:b8WCQ1HwBWYMV+I3Vb76Vw==,type:int]
                    httpHeaderName1: ENC[AES256_GCM,data:nCbQevXHdPNjPIFk1Q==,iv:+pLqlCNRB12E8Giplejju8gxl+TgMze/smcDlOK0T74=,tag:Yq1RcG7WAWl7ppoqAsJB1Q==,type:str]
                  secureJsonData:
                    httpHeaderValue1: ENC[AES256_GCM,data:RayBS16h5VPH4H01YtgkmnqeOqTNOS7SOovEsrZdVYujMLkh,iv:L2jb8RDqBr1/ErRByXhdNuvLo1jUoCrjzOZRGGsJr8M=,tag:OvCiQdJ0OeXFP8Pd9zcFGg==,type:str]
                    #ENC[AES256_GCM,data:aO1YG9kiPPOKZqhQzidCu57QH6JLzudt,iv:K0yjv7gTeCkLJdJBVJaxf6kT9wW4gsJHy+5DFs5quUQ=,tag:EBYamjMwc0sbCahsbsoZSw==,type:comment]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UjZ1cUo1ZVB2Uk9OUGJ6
            OGxSdDVDdTB5TS92aFJOWTF1UXlRQkkxRG13ClJjMlo0bVlyaXNQOGVrNmlMK0NP
            byt2ZTdpaXJkbmJ1M0JSSWJQT2VSR3cKLS0tIFE5NDNQOHZnTUJoM3B6a1NhTXRI
            TjF5MllWcGpoYTljbk5LN0ZwZ2pMdlEKgb5T0arli3XQhhddFsT+2UH2rq6AIZPo
            XsQcUTLLT7HRuDtyYh7CofrZ00Q090eHhPGGmSR55Vf8WzMMOz4sMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T08:24:49Z"
    mac: ENC[AES256_GCM,data:KrOtU7t+Dwo8aCL1btYHYkyOtiC1PdUqFjSTHA9Pbg/15pZIxSs+GlWdBhO3qKRN4ZmTVFCh5q2By66aVU6FxvG8jQ2S29Ebs827R9ldq19Ay8wapnRNr4ftO/4frHswPbd0n4PmWAZ/qev8hX5pHB9r3j+C/PJjqXDfMrTl08A=,iv:iBc9/dxmjfapLVDL/RZk1VYTeu0IW7/F9fKkozHW8J0=,tag:3N2ntlCSgMfWrV+cmVP2/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
