secrets:
    data:
        - name: ENC[AES256_GCM,data:IUaZ18kRdTZoOzlgXklhOddNng8=,iv:1ovp2wYlg6j3b7du+9uyBmB3JCNywqNr9FU5WXSfUbs=,tag:rINikiN8X/ahgvPx1gQjmA==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:C2OZpktExyY=,iv:j/bT94+WAgPZCs0W9RQJzGoJJoCRHFhByAQ98v2x6k0=,tag:FULUxyPiLKjJ62nZupD1vg==,type:str]
            admin-password: ENC[AES256_GCM,data:7fH0dEMaMGw=,iv:c8CUtfxPTfWpIfhpyp/hrJS7zr7Rbhh97u2c61SHomg=,tag:EiPsfXGz9Shp2UNMjztGyg==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:Qqd+9g==,iv:4yCywxyCB9Gpi9TxW4v5wqIRX711brZscPe7SfNhRHs=,tag:vbz0uAynOgCvEcHK5aKnmQ==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:0QY/uw==,iv:lMjfABPH74zWYJTYB83QTC4s7cYrAiPiH/gvvrSkYfk=,tag:kf5MzKZdlffrJ7nMtGsA2w==,type:str]
#ENC[AES256_GCM,data:gWVChPBE,iv:xvQ+6dUcCevJ37EuLCn3aEEFSzj/NtbcHEnlsCV8Mkk=,tag:ZiW+tbsp9M+1qX5jCDgvHg==,type:comment]
#ENC[AES256_GCM,data:Hd8HJpzTCc1QsTs=,iv:pXjnlzCXqsWbK/YWor7uEISzx+YLi85AJTpN94c7a8k=,tag:MYW0EG10BN4Ag6WUqkh5hA==,type:comment]
#ENC[AES256_GCM,data:yhoKMSdF3yVDmsUAovdi,iv:axxJAgPs4vf494T3/HB66t9TOTOdQAlli6te0Md970A=,tag:66t85MeTNiYiHl72r7gFyg==,type:comment]
#ENC[AES256_GCM,data:v6ZGJhaavyUBpkSaZA4M+rRiKO5o,iv:A9mRA/5pcC12VVjU/e1sCcIZG1X5CqwhDv/fj+WyRLs=,tag:ICRBVEfao4DtBTQJbQ48Uw==,type:comment]
#ENC[AES256_GCM,data:u9MEXdxDqTrdABeYzxbfmtIZYntX,iv:eLoqXDCA0H1TbFYf1qhRUyWwFEmHRcOdM2ZhTlCj0wI=,tag:yuLMG3XJKyGtn0SvACQyXQ==,type:comment]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQkJYZTd5ZTlvY045cis3
            N0dlQVZUK2dHdWVMeTZaL0NjMWUyS1dYWVRRCkdna0FETmg1UHV0eVNZT0pBRjh4
            NGdxMGZCSENtelFjQnlnV01iM2MxanMKLS0tIHcrbDhvYjFKUnQweGJ3NTZIZ1lM
            Ny9ad04yTnVTcjlPMFlnaFlIR05FYlEKNvqyWfXQEoblKw+Tjlq0wj1Y8/B4IgU0
            1qDURDWQFZQA72QI+RJICHFHpIzE3ee8mjQcuZkj20XJbvc1eLip0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T11:53:48Z"
    mac: ENC[AES256_GCM,data:xmxnIz/VixVc7o23f8Al+hSu8UOq4cgkU8p536jksHqVd4lVO5ZhSn5Pvef5I+YshCYgl1TsyZDp+RTCYCq4gwmtm29bFW6SozhQWl1RPXFXhlX2uPssVVRX3PernaFJ7/3OXAxE3F2/Ck+Ch5945kz+5xn/83Rryc8qgDfrFqk=,iv:D8IUJbOn0KEh8CZ6XZL720aDdNCPVjK5Jw+3KcUm2jU=,tag:ZBM+HJ3fk18knhD1BY4o2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
