secrets:
    data:
        - name: ENC[AES256_GCM,data:tdrLIYXVtWQlg16dDjCLryrqU/4=,iv:Xg+PC2tzD1MV2VTaNm5buoTBGNLxN93tTYGsCxIsGLQ=,tag:qV7qhXjyNiyVup6Qzux7jg==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:XloYO/EyKeE=,iv:XWpyizBxz3pHZATEDS4iQnsgjW3vZD1QXIHLHyq5Org=,tag:CQkoW54OuAloNE1oGfKSlQ==,type:str]
            admin-password: ENC[AES256_GCM,data:r+GmSMlwnp8=,iv:0oWD55NSkiP3juMmwE3dkzN0bQHW4HAnq8ZW7+toGe8=,tag:syCHcTHzpqrptDRIj2jVGg==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRE1PcUNjZi80WFlZaHZT
            K2FZZDk0Z0ZFZVZWOFNGbUdLMUdLaTFHdEc0CjBmakZYNmZEalNiV2w3VWhFUFlt
            S1p0dExFNUFjRDBCVCt0TFBuRWViYm8KLS0tIHZDTXlreTZGWVJZeVNSRnJER0Vj
            dUJ6RUhXakRFZTFEWnhMSWY2YUtuWlUKN6vjo9PB4gok7gkeSZiuX2pISb9iQq/d
            YdL4mZ1EAZ9IlJgvSYufC79/5+zYRPEkYCGVT+1X4QcsjDKMubdWqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T17:51:20Z"
    mac: ENC[AES256_GCM,data:jSSwgL64LyyIO3XtU1L5E+pZeHbcgmvddpfsz176ee8gjmnAccp00DKDtky7hXb9wewuWDwEDcTBNSIzdvNso+7vKlvSC+d7vLiGoTTafRKWlIj4Ue1Rkgw6QvGIzCf2NTMBEqoRIptSpKKxDUC1yWyJMwWtnthRCqMTWJ4psks=,iv:Pyaebp6e/YgAXYIA7Tcs/GOSosCjR2GQ3RXHu4FTDw8=,tag:zKeFSNhRB0wkJ0P7RJJt/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
