secrets:
    data:
        - name: ENC[AES256_GCM,data:8thGKUMk2TRJOCPNPBBCqR4C5Ng=,iv:JSjPBHc6uOcWRpptK35uMIMvK3ND5SoT17jitXlkpBk=,tag:fFT6pjt/mlLFgNVjpvBQ6w==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:7fEEIds2GG4=,iv:3eUbjwezYPh+KTSh6C1seZj8igXV8b5MynuC02srvjQ=,tag:7NQ77f81gxbsFOieYBDxKw==,type:str]
            admin-password: ENC[AES256_GCM,data:mTGvoNR60MI=,iv:HZc+pBv4a41roXVhDP3fQIIITLvP7Jiux7yEL3HlvBo=,tag:rbqe9oMUmtiXbqUOzf/h4A==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:erAq4A==,iv:y2+onvYvvCPjU8c8toM1lZ20PKXAXkqDLPlWuSrXVH0=,tag:tSpFXF5iW3CE2SBMxWuIGQ==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:dmFwGw==,iv:me9VxAq5msssCz/1Q/hScHkZiQArS9Zun3ykkEE7Gjc=,tag:YvFKVB3i17rVlC/2/EIkMw==,type:str]
loki:
    gateway:
        basicAuth:
            htpasswd: ENC[AES256_GCM,data:D97lOCBsEVcOJwXZrXohcEMdhzLPYiAJ0y8rQ5jm,iv:ou7t9FI1ArscOg8SZCfyerY0b3b15JLn+S/WOqb5X3w=,tag:qRdN7Rqy0WlV2RiHquqUVg==,type:str]
grafana:
    datasources:
        datasources.yaml:
            apiVersion: ENC[AES256_GCM,data:qA==,iv:KphfUjMYSU17kPV2FLknTcAIL/S7wsfTGjAWpmSmISg=,tag:x1wAViN7cLvMgzhP901oOQ==,type:int]
            datasources:
                - name: ENC[AES256_GCM,data:ByNqRg==,iv:kmuNnBoosPG6M24jba3Qn1mWmZWCcyiy45k4p8Lcs4s=,tag:ypXpk2AdYm7tN4tHVOsD2w==,type:str]
                  type: ENC[AES256_GCM,data:G0MuDA==,iv:GXA3EKpcjhmVGu0Y4XX88UBEfaRX31f7Mofg6G6PBH4=,tag:iSn2wX0DGhgp3xy5vNL2qA==,type:str]
                  isDefault: ENC[AES256_GCM,data:dGy+Dw==,iv:op1bgz9Qr6YBUz3qrurPZUVVy3z8wtrFrbVKKvG+fdE=,tag:TtCD9AMH9Ic0AEkFl2G+Vg==,type:bool]
                  access: ENC[AES256_GCM,data:JDR3zFI=,iv:sXNErWAI2WwJyJcjP/V8Ds/T8h8oIkRowZRCqZFCngE=,tag:NGg4O7jnON5HQMJn3Kbb9Q==,type:str]
                  url: ENC[AES256_GCM,data:dy6NYCxfFVHNlcTKkgf6TOP2qh7UvytqMzCu1YMLKrzBnne+sqZRg47UpBVBo9cLB9Nlj0Z95hv3NLRewl3K,iv:yrDPW+myTPoCg62JSG5n1iVz2cZJeEDnrF7/w8VcMms=,tag:dTF9gmsUX6/AdxJ+ExKPEw==,type:str]
                  basicAuth: ENC[AES256_GCM,data:ZWu3rw==,iv:wmY2c0ozyb5w+ffg4fzrFWHs5ilOgw50L0csAfu7j8A=,tag:Zp5YmriVTRz7zixzr66L+w==,type:bool]
                  basicAuthUser: ENC[AES256_GCM,data:taHW9Q==,iv:9q0l2JOySDXr4bKbBhs5CFfqNrt2b4GhJLU6jHisD1M=,tag:r8N2sq6F3803w+5OUDaU9w==,type:str]
                  basicAuthPassword: ENC[AES256_GCM,data:vamRug==,iv:VGwfGCtL3SwCwHjbKMZBqvHAm0ok4aKNjCQhttt01UY=,tag:DgdbKyTRb547rPjVcdTCiA==,type:str]
                  jsonData:
                    maxLines: ENC[AES256_GCM,data:GaNcpA==,iv:wjRMmEQ/5WNt7yDxlKykxz7YhbpafPM80BR3OMPzXzc=,tag:3ok0Co97BreN5VWi4AtzHw==,type:int]
                    httpHeaderName1: ENC[AES256_GCM,data:8V5FPpI5wjKq1xY2zQ==,iv:Cx/bxgp3H4rcAC5YohYhA6HXATOKDoaK1K51nzt5W/0=,tag:AJKCfaCvvmfSaV6SxhhjbQ==,type:str]
                  secureJsonData:
                    httpHeaderValue1: ENC[AES256_GCM,data:LpMv3QNXiAwFnUrlh7LeRd0/6g5+10X8zeGrAYkiNzNpIvRy,iv:BodjHajZ42oh8Q0O1ouWnGtKWF5juCO1AHS7ePrGLS4=,tag:NYM+oLKwJgKi/b7QMNvneQ==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUVR6b2tseE5qaVB3aDZq
            ZGNmekFQaDYzWDVRbk9WZnVuNDBlNWFoT0g0Cm9EN0tnK2ZRSXhQVHE1NnBGeWRl
            QTZ0V2NzVEROZGdLVGVOMzRSWkhPNU0KLS0tIGpnQm9GeVJQYWhPcGJvVWJ3UzRK
            TXo3bk9nRzVyOG03WlpvUEk4eVY1aGMK47FjLMaHoMgvWVlm6QYAwobHmorC099h
            xebP0S/wTpQgoKbZeDlQZDMpcQagib8BL6NBoh2boLXyfEAqTbHSPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T08:01:12Z"
    mac: ENC[AES256_GCM,data:MnGKqmCPtTxaPv8LVDvGT499RXttbHyasXMJ7KdIE3WW/1EgTQ6AZuTusS04XmmvlPXBZ5poyRp1nGmPB/4hgGQsef4O1Shyt+NxXNKYz2qidz6QR7QbhD4xFl3i4bFtOHFqaQGr5jNSkS3HLT1pard6vL68RUVMo0M2WCA834E=,iv:GDXNR6TBau4INnr7AbhFAA/Mcj3cBghUMqYNVCzMAD0=,tag:+9Ji1DDB1wo3FYCW36Hb/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
