secrets:
    data:
        - name: ENC[AES256_GCM,data:G3ua1S062bVR6+/koNb6olAc5wE=,iv:YwnljQvOK51QiwobiIw++N46MqG6LTwnszJvtq02KiA=,tag:8XxuFx49cn7jkUD27B/bDA==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:dX3Rlz1OQXM=,iv:z1V8T/7b7JJDooFVGaDtht8D9HHR9imVRemKcIjqs9g=,tag:PLT+fhKi8kQFmfHrPCt1dg==,type:str]
            admin-password: ENC[AES256_GCM,data:1ctxGVj3P8A=,iv:E5Uz1m4K9flxu9agUMMS6Oj1tIIcMW6FQw5T859KKBI=,tag:gVRGwxuHRaafs+qpqNHUjQ==,type:str]
loki:
    gateway:
        basicAuth:
            username: ENC[AES256_GCM,data:RchaMw==,iv:SX0ktnLkI+EZ9myHB/vWt1HZH8+nyGku8yNV2p+MsZ8=,tag:T9I2e8bHC53xbnnkD7LZwg==,type:str]
            password: ENC[AES256_GCM,data:NbnZhQ==,iv:oOmyNeebvTLAsyJ+JKiKGKE+2U+LZJVF6sQbwxX+a9o=,tag:ZEjg2lmiFP9FtAE1KsVlgA==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMWYxSStrM1RlWGN5RXZm
            a0lhV1c1YWZBRkx2NlFtZUlINlpzOG9IaEJJCmt2alN3V2M3UnNpZks2T1AxWHQ3
            a0x3OG5YUDdHRHUzNG1oK2pydlhHT2MKLS0tIE9kcUdueHpsRnFYcnE0SFBmYkhT
            bzIraTdJK2YyZnhVcy9jbXBLbFVMUmsKYWcDkYg0+xhdCpklEvYTfu8n4C+3nOOF
            4+F9t2DZtcvn4UirRsw0EMnlvioT2lz+MA9KnowOwVyg9sMdpJtByw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-16T15:30:34Z"
    mac: ENC[AES256_GCM,data:HRVcch2jXCJvgvHMurHz/ryJ825ceXpkz8rkVhN3kMaVsDtX8x/6WUNZGaVaVzkWqjTBSrERmQc0lFu7kCPdqaqYKKN7kkFj/mecmDGz6s1N2VaqrqzwdPBnYjNTr2vu+mQaBPm9+qkLVslAoerOuL+N2wLKEzLn4hKN2oWzfTQ=,iv:mVPLPfY0x2qc3tg4CP6/mJffkXUBXIuzWlOACppvMsM=,tag:FN7GswaglD8Dcj7GGpYzGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
