secrets:
    data:
        - name: ENC[AES256_GCM,data:vxOPppxglo6RfTPZ7sNQqJOw6aM=,iv:Aoow098Gz8FIBZK4lU9okqsifvSOICxXBeGJnlhf7l4=,tag:U6cvDbiZKUqwlYEOwwaAeA==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:9ya0dzXtjOY=,iv:Nyk4/679p5BL+JOaovBfaM0kIFWHN4No2LPca60xUNM=,tag:+uzGUfNSp7P7c52b6ryEEw==,type:str]
            admin-password: ENC[AES256_GCM,data:d8OispmE1uI=,iv:ZcBGI1ZD9iEM6HL4ZYkIq9QA/7PTAth9DflFVoask0k=,tag:gSsDhNK4/g3IPvvZ5OHIng==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:IFgdyw==,iv:83Rf031qD6QAg+XgKPJiMVqNNU1eQVRUHjgAoK0fsZk=,tag:mADrDH3B0XrnXDzGW1YIcw==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:qlHPxw==,iv:ROWICRtISjl9G/0wiErPtDoHCKAVavgs0jJePouKahk=,tag:HP2yn5VrOlnMpnkK3MCumQ==,type:str]
grafana:
    datasources:
        datasources.yaml:
            apiVersion: ENC[AES256_GCM,data:1A==,iv:ivEvV149OX8AtScSt05eH8rpUFZGQDQCq85OfTRKMrM=,tag:fOE/PVoXcQmwuyYhFokVpA==,type:int]
            datasources:
                - name: ENC[AES256_GCM,data:2on/rA==,iv:hzaZl2g+PFTnrZqUOXCRHws5wE8jYp8fO//FRXJPnyw=,tag:lfLdOY1Hl+dNie5GgI5y0Q==,type:str]
                  type: ENC[AES256_GCM,data:etSOmg==,iv:rADv88uGmkTvLG+RYNh8H2yj8Cd/zB5Rph48lefBy/Q=,tag:h7DNVMX+VTLrAHcFlrnXDg==,type:str]
                  isDefault: ENC[AES256_GCM,data:Gy1V8Q==,iv:AoQOStV7kLy00K7NlbJOjDEMR8XLiaLs2UDSykjrraI=,tag:ybbvPk+R2LLkgAfRsmtrkg==,type:bool]
                  access: ENC[AES256_GCM,data:3nb0vS0=,iv:0ctn1/LDmTP04+TUduarUAnlqLPGQqq1AM4VTy3nzXw=,tag:8qI56wKoAcqKYos0KIwM1A==,type:str]
                  url: ENC[AES256_GCM,data:CubVYd34p+la6pFDTMm9XTUhWDpnbBBx2XeR75fOXZar8StPZBa+HGSMLTss6BInDhC+0NwrMm283NCWuZ7k,iv:PGNn0t5jlwQTTxTHih6kxwFqLuldSyZESYL/FZX56wg=,tag:2qDejcAyt1OkSjJMhRGWYA==,type:str]
                  basicAuth: ENC[AES256_GCM,data:4TvQqw==,iv:CrsbqR6GjO02bhwcGi7CRQn3Fcaf6OMXrPHonXz4fTM=,tag:StSTPzxPyew04iQuQpDVeQ==,type:bool]
                  basicAuthUser: ENC[AES256_GCM,data:hJAr4A==,iv:HPsOkEaGeu9uo1YUGyvk0vReQIuYXt55HMQt3C6jZxg=,tag:giXfDIpAW79Q9qzMlQ+v8g==,type:str]
                  basicAuthPassword: ENC[AES256_GCM,data:XO1qnw==,iv:q2Ga/gLJrlikUUff5/E8tJDcKdJuNRsX5TqTGYN2dww=,tag:pHeNsZQCOtSIK0CQvUGQHA==,type:str]
                  jsonData:
                    maxLines: ENC[AES256_GCM,data:BQOHag==,iv:I0UyzMvDMvc2f8+vNYmfSmWAeuCzZ7qojX8oa8cSGDY=,tag:m5INcKW66tl9BargLDqWWw==,type:int]
                    httpHeaderName1: ENC[AES256_GCM,data:EKxaGohR3fBymQEoNw==,iv:t0riTq11i2OAXYrzeqGvFLQyLxLfOLN5dpNzTWIRz2g=,tag:NW8CfBs9zlp+LeipPwuWfA==,type:str]
                  secureJsonData:
                    httpHeaderValue1: ENC[AES256_GCM,data:R3pr/QiHg0Np5HzmKoOPRaSrDNVGTSXrn8uzH+fP5YIyKzFT,iv:qWIPwXpCdWTvfls99iJAXjgPscJa9O/lhDIJN/Omr74=,tag:itRrg81GeGh5qIrGxPMRug==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMVpXRjhpL0NucEFUUXhX
            cDNEVE9vbWtoMjVnb1ZCNVdkZ3lmTUp3dWxrClNVS21qek1OU2xFVUFHcEtEcmw2
            NkVDd2hHUEpJUmM0TXVpL2t1MmVKMm8KLS0tIDhMOSsxK2xMSStSa0VSZzUrSkYv
            VFpuaWpMTHUrVDFCbm95L1B5ejJiT2cKd3XjvxnAr2IFfId9J7XDorHvGXCdprRV
            vOtcyTD0sQ7RaMM41+1YnOAwiWVMin2x9c2T4zIcZ4QIWIEcv6A+rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T07:44:30Z"
    mac: ENC[AES256_GCM,data:jUqU1usVYO605n6TqA7qasX+GEE8oOz4voaiUlEMZmanoKDYwiIYO8W4Tcdfkls5Q3RLRWzn/Zvurn+pgjr+kuGZy/m7sssQfzqLQzXBIbDcZNRmc9Bw7pBV33nrIrHgc/G6QL82fZa5E2DUvOs8aQSJAz0moE50pZKxBawHAlc=,iv:roIACs6sxUmKhMggEZPwafPPV4e/evpufWW6mOZowyI=,tag:RQAhdifq8WyLb+mqNE3VCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
