secrets:
    data:
        - name: ENC[AES256_GCM,data:xexjeMZKb04NcSLr+LpRbEtgx/U=,iv:dsKxe2hQKc05iCk/FF6SZd2/QvE9+EpDEQpW5xklDu0=,tag:Vla//rIrrzWo7ehQp9Cg+g==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:2WkBkEqm+Pk=,iv:1J/Z9DDazJx20VaMq6kGKlpZj90nn83ydyUAltGFBfY=,tag:fbF77wIJ0LqyN6QBIc7chw==,type:str]
            admin-password: ENC[AES256_GCM,data:PIUAxemGFD0=,iv:n4yD2KKHhpe7yoAP3o4IuAiiIulby/jMnfhGBBGNevU=,tag:cedjAoz4GztkHL4nvh7GYA==,type:str]
        - name: ENC[AES256_GCM,data:CoFdqR4npWXeNG4cfnHykqG1HQ==,iv:I6Vue4An/68CxWxbA2zOX4Ck6Ov/3OgWOQcfkZceALE=,tag:IFSHDXhd/pZJ0TVNbgNrMA==,type:str]
          stringData:
            .htpasswd: ENC[AES256_GCM,data:zBCRXCfRtKOnJoDHD2H/bZZSv3dgCrfh5THKhZMIZS4F/gEtFQ/tJ/doiQCYZm9yLCUulA==,iv:di0/NXjvBMx+iASmufCp890u5PWvk7ou1ZSmPkuOOVI=,tag:daloq24jpZCojiifh6jxeA==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:jD6Ceg==,iv:OsPGj2DmW9Qe8Kdkj7Y76oi64VDJvIVgxo8Suy1pNwI=,tag:aromELZ3RGCLA8cInGkbjw==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:w3Rzlw==,iv:JD6j5736e6feWLqVy45dysFFeH7LJflNqh3635iUO2Q=,tag:80KOyxSKGbmAN9tRkmg51w==,type:str]
#ENC[AES256_GCM,data:77f9o6gn,iv:cNKU0PJ9qcG3nJzhqBh+QVT/4RZKVDrNO78VmADrPGM=,tag:1lhgc4dEjGDf2C2oz5dHfA==,type:comment]
#ENC[AES256_GCM,data:cwE10+bGx0REzWQ=,iv:7IZmrPY6y4HmSxrwFOMQbVa/2jVEq8i3iKw5xHji9rM=,tag:tJ8qkN+Fl6fcUhBZSsCopA==,type:comment]
#ENC[AES256_GCM,data:h+FihtVgGCTbtMIiEe5j,iv:JIdCRGSLzz5ZXL+aA22zsokK3wQ/J+lxlE7HBa6ET/U=,tag:96gC7xLR1K9EemPqAMr21Q==,type:comment]
#ENC[AES256_GCM,data:3RUr+O0XxyaoIxuMcttM+tZlBkQ=,iv:9s1CUKfRyadfU9JKT635jaS3T7R55w2jJmwnZBtGVCw=,tag:mAWF0lTcRk0OTMwhtorQtQ==,type:comment]
#ENC[AES256_GCM,data:qPonjr0la1Kik+jqOSA1wU12r6giPg9xFOS5pxiyDKZvNs0I0C4pDyy65FaHiFVLNU/VxO1SrlpjLs/s6g==,iv:i2cA52aG/Q81miiq49UPHatiDcKCZnGxUGlsUFSK2fY=,tag:o/RiReJqr2hEk/Cr3tfdPw==,type:comment]
grafana:
    datasources:
        datasources.yaml:
            apiVersion: ENC[AES256_GCM,data:+w==,iv:5AwNtuRvzgCCwUPfRcynCa1m3CBbNPrrDCYi+Qun0so=,tag:eD8r4rZLGMLbyIO+SbFBcw==,type:int]
            datasources:
                - name: ENC[AES256_GCM,data:gArOCw==,iv:NSDCsTZOhJ471v+P7KmnWmDTzuNxmNIs2tHuuZaPTR8=,tag:F8SJI9v5ET+rDPWCYCsKXg==,type:str]
                  type: ENC[AES256_GCM,data:3cg0WQ==,iv:AAx7+ZOuQyrrgUSJcW7JtYjSrcUxJ7nQUPbrZJG40fE=,tag:VNXIt3rd6ErmstsHkHHTMQ==,type:str]
                  isDefault: ENC[AES256_GCM,data:gLHVSg==,iv:M7m2VXIyXgqPw40X6hRUZEe6wQlZ0po6mbYtm/8nZGQ=,tag:Ra8VlEYROrxT0A7AWwrdIw==,type:bool]
                  access: ENC[AES256_GCM,data:LrkaG/4=,iv:LACAbYdz7jGqvsmUqgHxOmIHw4RK5htGk1OtE44VOJY=,tag:8abhxsXf52QoB0jXXNs1jw==,type:str]
                  url: ENC[AES256_GCM,data:nM1iYXY+0zp7ZSHW4iNIWzUeF9uF/gWH2HYHhpkt1yt/N4IqWygyMpxsHOCZg+XC1qdsuFt97oZxto8XQYrj,iv:C/xGgITtixu42kR5a72Ikz07ocTiX81dyTUd6Aulskc=,tag:Ph45QzlHfvssvS9okTs7HQ==,type:str]
                  basicAuth: ENC[AES256_GCM,data:XP+Iug==,iv:jnl7NaOM1nsBvocGJV6Z6BgUBAUSQKRf02pbebYIUEI=,tag:F5M//XOVs8GI8Kmi+cuaFg==,type:bool]
                  basicAuthUser: ENC[AES256_GCM,data:iMZHTA==,iv:qF00XCdB+q9m4xZE73QZiqXJeD0/LE+y9pIJ0m2jCqg=,tag:Dmp8CP+VKHe0abl3YpgXTw==,type:str]
                  basicAuthPassword: ENC[AES256_GCM,data:XTAZVQ==,iv:tNthbbxY2nTe8teL/G5kp4cVmDEqQjyhrmwCd49YwEE=,tag:pyuQIjYman5IdynSa77kNA==,type:str]
                  jsonData:
                    maxLines: ENC[AES256_GCM,data:uldWXw==,iv:x6Q8RTidkGo0us/dgArEE8gUZnNyM2QSQOtMuThzqD8=,tag:uJwgm3CO2r+4EAFodlmcKw==,type:int]
                    httpHeaderName1: ENC[AES256_GCM,data:eKCSPtNi+NZHymvzew==,iv:qSanNYc0c89gg9Zj9W7FiaOej8uVanZ2RxQ3HXu9z2g=,tag:5L5XlY31HPsLFTKd4PSNYg==,type:str]
                  secureJsonData:
                    httpHeaderValue1: ENC[AES256_GCM,data:1VBMp0A8V0A/hHTo/GF3VE2YcvLujjbyS2LQu8ruvjTlR4PO,iv:nVoqxecaKsLWLYymwnG693I2DunF+XPHwfoy+OKoNwY=,tag:v4WbUklnfGJikKTYNZETOQ==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y3ZHNzIvTkl1bm45dTN6
            VnovRGhOTnNZdmVKZHJWSzNoeGJWTFZxTlhjCkFKa3FOTitrL3c5dWVMRlFDckF5
            amlhNlhWaEVCeVNUYjdqaEIzMmEwL1UKLS0tIElhdzdjQVpZSEFwK2tQZFhkVHQ5
            WnNVVU1pRTBHV3lpTUVwNGlkYzRMbXMKtyjJl1CJQPoZO5aWU7KMAiCSzXwVBATL
            RoSHUbvWTaLg9kbVlbIGY4Jbq0HSTfld6MzDDPfhCS//HtZD0Oy1Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T08:17:17Z"
    mac: ENC[AES256_GCM,data:KsdHS3wboPUjg/pRc73y1Nv81YS2FYh/dDrKZTFaDJquGpiuyPhSDByFqw9aKOzgavcCGroZWXYCx8w3RWmVTC2zkSOYoLhpku276kLL8XyZ94mKIZDcJrRBysFL36/QAv/CFjrpobhPrFL/sL6KlbWD37YIvhbOPEhscNUqBb0=,iv:c1qaq8vtTg2arBSDnPR5pnItqkIczGY5USz47IT3H1g=,tag:X4z2rXLac4HnNJWrOytEAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
