secrets:
    data: []
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWHQzTk9LNkxFVWdLSk9M
            YlNtcXUxUzcwZjM3cDRzRXNpVCtvcVRvTlZ3CnpYRVpVakp0UEg5bE04VTJSSHBV
            V2Q3cWxUeDd3WURpYzlUTHF5a2xnRWMKLS0tIGI5QUtwektnZ2pFZ0ZGdW1lWXI2
            WU9aQzd6cGdWZzQzOTJPYU5FdFZXZ3cKjFbVdnS3SuxhpoXK5fRpYTjLDzQhbJTI
            H+L7a9JSVX2p4V7XCer2+T31HcTrgH9kDVBg+3GE5B/KZq9JT5g1xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-08T14:41:28Z"
    mac: ENC[AES256_GCM,data:TPRIGXR4LQQyEayyaC7JbYbjayC5l7j/zvFKs1NFljQns/S5doxRacp+VXcPEp+JCuCGOnIWl/PSde9cEIs+lcLm8yx7ZZUwRfm2VpWstMoeulzo9ofyRPJrgdOeSGD5HwCsqOsq0v48NwiR+pEaiLkg79e4klcWrInMZk+7dZY=,iv:/bMa1sFDtpV9SsgazAJFT1634oYfPG0qR6cbs5k0tyU=,tag:u6DiOpHjXYPloRdSCyuBug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
