secrets:
    data:
        - name: ENC[AES256_GCM,data:pPdMGmie2d4QqDmrbkMsnFyne1E=,iv:vaAsWv/7mV2u5zmV+UfFq5Tx7JtYesBm0Qivocq4sGs=,tag:bVZrbK10BPfL8tfNYMSvXQ==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:BuhPQdjO1iM=,iv:81VR61/tMUYUL3Udu4j9uE/UK9lks+tSlgOhdcGO57E=,tag:zT1iQ6/aLTQeBQ5LMha8mQ==,type:str]
            admin-password: ENC[AES256_GCM,data:hkA6xA3lvvk=,iv:24yvtwKHUC8FmtlQRN6oflu0o+0XuUMCR3KNiyZHIJQ=,tag:YhbDvrl0WZnN7NFUXieZZw==,type:str]
#ENC[AES256_GCM,data:Z3pZjZW/8k4=,iv:4uq1VVXZTKRvD6Yux+XyoUr0qo9rS0sh3JDY/uYUt3s=,tag:Jh7x141VstuYXK7Y3n2XFQ==,type:comment]
#ENC[AES256_GCM,data:OxzsFxgLB3w=,iv:9yzMjtJgKNneC6vZ6miZmFOhfRlq4VuLF1PcVpUYpwg=,tag:7SqxGuvV8EXwuqQaevgstQ==,type:comment]
#ENC[AES256_GCM,data:hKz3nXRODwX4UaEt+gke/AFR31/1xQ82Vmpb5g==,iv:sKiDpH7mAYSjoXI80Udnov3m9XJz4lyaqnDaRd5mhdk=,tag:fwJ6fRJ8obCZc7DIhyerkQ==,type:comment]
#ENC[AES256_GCM,data:kuqcPXwvfY+FYHbTjJS6OZgvo7LwhOtkndRd3w==,iv:wbwuvM5h3qTqTxu8ny6jbwq7J0S0HvUeWBmjwAz+a+k=,tag:+9qhTG+YssXQgeo92td9Zg==,type:comment]
loki:
    gateway:
        basicAuth:
            username: ENC[AES256_GCM,data:YedeCA==,iv:bPlJjOKwl263liHjCuDgKu8swSBEYqZOLrDvKWO4nks=,tag:5TAEa8cqUuDnK6S6o3/fzw==,type:str]
            password: ENC[AES256_GCM,data:LnocTA==,iv:oOoeC1QHNwqZzsFul//kOAjSCG92vMDSDtx11ufRSAA=,tag:PJUoz4xy+djnlUk2l95bVg==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OGJtRFAvY2ZUUXZGc1Fh
            UFRoT2lRTUwyelN5Y3B4MnMxQWg2Z1hIZkJVCnJQU2cyNDdjdVJRZ3QvYk90enll
            Mk5YMmtRNFdoem56elhZZHgxekZ4dmMKLS0tIDdLbURpNDFBb3EwSXVST2YrRHQz
            QmgzMkd1c21ZekpuVFFSaGlGaXlPUU0K669QZ5ocdegd+ybIU/PngfT2djnN+Klj
            hl0PxFU3rS3nb7z3w9APqR3qkId8hBO7FZQXHz+LOgD4UFq45OfYSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T11:58:30Z"
    mac: ENC[AES256_GCM,data:0Zw5OIij7lSgsROE4kRRHjBRqSysngGSVvMLYfOLjn5xOBS6Kc9GvGBAFnkAsIzWlEGv0kyAuzWiIqMO0sPDU4tg0KiEj0q2a9SoeAG7clec4yJy/4Y/QB/izEfPgRuQvoQ4EsytFIYLHvqlrh9Tye6Plpfz63gt4yQGhO8U9RQ=,iv:gs5L8MazlYmtrQ6WXwl2zazV3S3icLB+XzVbJioeX4I=,tag:aXY19Y6HBiqX6mjwifSTUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
