secrets:
    data:
        - name: ENC[AES256_GCM,data:wCOWsULsnR8buHv+sdegKf3xu7k=,iv:8ed6VyaO+709EJpY4SLRaxnl1cBzx/QogebAn9Kbrns=,tag:Syf5JUdl3Mk+r0MmmIX7TA==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:op6KHeFcY14=,iv:yUq+V4wn0xRZGFTDGZycbndl/fC2e6RPx6drs+8upEg=,tag:V5+0oFReunfvbx40vnsv4A==,type:str]
            admin-password: ENC[AES256_GCM,data:QKO2js5cY6A=,iv:vReQRxM9NKF2lMjAFiwmLoCg5SbFW/tgKEKVL/U4AWs=,tag:ek9tcHODM0CjNYBBI9aYxw==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:G7K40g==,iv:PCisWLA4DabndAYq+bT3//uD0mjH7TrFcbFekfEboRE=,tag:1Wn4S+H+LqyIITd1/xdeKw==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:tz/1NA==,iv:OXbj5YL+eHBlRco9K8qa+3FFAHZVspb86/Ig3GweAnc=,tag:AbKiezoVoFAw8RkAyQwkfw==,type:str]
#ENC[AES256_GCM,data:y8wS2/B8,iv:ZZPuSfynhu/oAMtIafEyzLyBNxfGBYmtuiBBRR9ah7s=,tag:izMVyxtTaoI2fZp0rhTcIQ==,type:comment]
#ENC[AES256_GCM,data:/TyDQ/c7KAvwJA8=,iv:ZRLiCyNsZIX7WVIbr000vkA6R1a++s0t0stM+ny6MQc=,tag:yTHr4FxtXi1eg2YewOz0bg==,type:comment]
#ENC[AES256_GCM,data:WI6uOR7/YfgNWSQFtt+J,iv:rBigWuETiXzPmteSZyh+x642cJHsKK6DJdFCs9m+8wA=,tag:5pJvSIqECeXjkcikzQxY2g==,type:comment]
#ENC[AES256_GCM,data:zgxtkqUy9Zs4bKueqpcvhwhY9Pk=,iv:c/aNo5sr4AZ/W7zttlUi1acARuXxFyRA1HCzG7STqkA=,tag:W6cI8Xd9DHvnmL050S/xuA==,type:comment]
#ENC[AES256_GCM,data:fy3zBtPcO7Oal4TEXofjeOjbVqB0W5BKMLXxEtEw0lvFeqUTT6pLCMHx8YSlMCgqcPRJ+Qu1yLN4Lisunw==,iv:ZXlh5cBj+FVx2eLuBEJfFKUZKeAU+X43Wp/5SYDDooI=,tag:73HD7z3zOAk6zfffwjzPuA==,type:comment]
#ENC[AES256_GCM,data:yJR1dKJrLnh2,iv:Bbs1wMI2jEEQIZWEnAR7v+HRPJArZjL1WJClzNeIF7U=,tag:dkt97O9LxwQRSbcBcSw2Rw==,type:comment]
#ENC[AES256_GCM,data:TOMAzAZmPwYAsIXwbZx7,iv:iqF6TXTSF2MT9DJgaZR9rRgGQSpWlgVUbZCoru/4pZE=,tag:VnlDyFXQtJV2sLTafu/ibw==,type:comment]
#ENC[AES256_GCM,data:7kHd5ZrQbILMRJrRp7BlVxYb6ksYYA==,iv:JX45VRQ1gWp0dDmdZlJA8cg3YHpCDCp58xoW8Jqk5/A=,tag:lLSM55rMSzNzT3yoB8LZ+w==,type:comment]
#ENC[AES256_GCM,data:csBL6qEywJLsDcwali81OqKFCUU=,iv:dusepXjxvimZB2mB4n/fXeLl0Zlv1CBwam25ocPO9xU=,tag:9b6ytud4in+jf/Ya0ynGZg==,type:comment]
#ENC[AES256_GCM,data:rFb4CAFSYur+uK4f+vEQixav+A==,iv:N60tdLMb/l06MraWXez9zBchkqYSYW0JiHImw+2rKQ4=,tag:cYo5qSsYsOcL4SItu+hV1w==,type:comment]
#ENC[AES256_GCM,data:YjaCQN+NFqicH2g/oBj8LkYEsOU9,iv:wtdIIm2pI2P7+WlTBl709FUMUMsqXy3eSaagqY+Y9Z0=,tag:T4e+decocnvc5tRlUL5Wew==,type:comment]
#ENC[AES256_GCM,data:Nf+xuxGI8NwYgepxi+0FM3QjLzkr,iv:ihIiUC2oHfQmgvaFSEV7RjcRCDIt6eMawLsROEeFG4U=,tag:6hbdJ/g628lrKEr3sc+mdg==,type:comment]
#ENC[AES256_GCM,data:DOz72XmziStYdS+tNCTrLDAwF3BhbPrxwvc=,iv:TG0IvCjlalY43IiH3DpcfT0sBli0zsjF52jjm1lG1pk=,tag:RHX2Kpt3PjjpWGmFl6gIUg==,type:comment]
#ENC[AES256_GCM,data:2U4edCVQlWuDrnLIcEv8JEm4iad2laZP,iv:Fxq4CzBydwiEa+r3yeYW62FAuTlLq0I46+0MXifyUEE=,tag:g1OvXFy8QkUVEUhc4tzd1A==,type:comment]
#ENC[AES256_GCM,data:ZE8lwMF59YHmd4fK+exonpDaP8mFden9fJ3uLrf8E1Y3fKqY7ZXCy3mzUMDacWp9rp/eXc390EilNCPMCGqrigMHGdO37y5vvNUZ0RIt0w==,iv:1fYthVB+53Yx/HGVaXML8hqRsuH180Xd/cIdUvM62cs=,tag:BczTsBDhM5wpaDJzByru1w==,type:comment]
#ENC[AES256_GCM,data:Yu/jXZm0a1Pq6h36V2IR2DUzh7JHSfOc2eE=,iv:mJCkU1WlYob95wgja9RSc3de3Z8IwJrQsDcXroFEmt4=,tag:DgbE4V6MYD3aPak+BqQIeQ==,type:comment]
#ENC[AES256_GCM,data:TDjfxdaQsJht1bE5L8SEfAFubwKox6x2wS9ZkSvk,iv:lIYfFXiLm0dainvnAJstvxvRlkczeOSFPkJ/EqEMT5s=,tag:uaqMBKtD+UJSv07J3mdr9Q==,type:comment]
#ENC[AES256_GCM,data:yqf/cx+Un08N/mqkgaxw5RxujzO+7NWXhOT7G/+INbKecQ==,iv:XUFdVo3tYbu+nu7q+uhem3x7WY9Thdxbq8AbcveuG2g=,tag:VTgavVfbjBeQTG9a7B1Htw==,type:comment]
#ENC[AES256_GCM,data:TBD0pI6yZ8tcc2q799VMUp2qqfE=,iv:hIaW6eVQEWJ9bO2RFE2yYlOaU1+trAgLAQIqFIYyMC8=,tag:Vel5sPMzGOre7HTsbit0og==,type:comment]
#ENC[AES256_GCM,data:aFOql9h2tuX3Pn6t5tj2U1sIg20QEwYnT1Ic,iv:xr2mjTI5WFTzU+RzC8PDiOcX2k1lR3PzyvEjrxTx9yg=,tag:bPNkdu75QV+3DhIExg4A1Q==,type:comment]
#ENC[AES256_GCM,data:klVCQK2VnkmNwdjNwESFBF6/hUtyz6eCIp1/6lae1a06McwV6ucC3Dk8DQ==,iv:xVYj65hG53nEede6Vy9oNJJSvFGFV+5dg7QTPGaz5oI=,tag:XNc4yAlVyI10jRfB9v4IKw==,type:comment]
#ENC[AES256_GCM,data:d7uaCPMUXbqld+jda0OoHVI1znazZw99N94=,iv:WgNTnW3JhX8mwsqeaXKdEifz3Jkz99o9CXe1Jztny0I=,tag:H8pYV0kRBfAhN1+9qep+3Q==,type:comment]
#ENC[AES256_GCM,data:r9XyU566i6XaeKqInmsEMc52mmvlrvxAu4sVlVEz0xCkJ/+qTL9rVNZC4MJBSQiQrrgCMORsuLT+7zryJ6kEXBRVsyeo,iv:1fsx3TGhbFG1DJHGnJmga6JVKFuXSyZ5Su50eru6/aE=,tag:iw04SbRl84y+1W7xZR4hoA==,type:comment]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdUxVQWhNZTR1SXZ2emlx
            M21nRVdrODNwL1k2cVA1dWg2TFZ0eCtFejF3CjNUc1hDQjlrRTM3ZlFKSzhFc1Ni
            eHlDTXN0SGdmWDBFcVRxM09CWnRmeWsKLS0tIDA2R1hwc1FWRXZUVmoyYVV0Ynkw
            Y3U5WHJoZlhjd2tiQis4L2UvRFp2UFkKe/1UHG4nqX2JNXyzaZPefg+f+XG6xjMM
            73Gk6cnoRVjDPYKzP5aX7vruLK8bVuWPGhdr0yS2mDe1vnUPJKRmug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T10:55:32Z"
    mac: ENC[AES256_GCM,data:CnTtPWsAPCcjivhIBM9RkZSXKbFlktAhx/hpRLUz0bKeNaW84b6yi5iPX74Joaj6zblBauOqMRVy83uihgYtzxmf7pXUgqDOg6g3ZCwJpcTyVjnYSG5pUstVnlnJjE2ss/WT2DskYtIep7BK/yeFVbrxjkQ11N28tXePEo0rvoY=,iv:0O1Xn4e8jAs8GetwhrKwVZgnBpFtHiGMn1efOTbYEt0=,tag:a0nqEMRiYyaXguheKiolGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
