secrets:
    data:
        - name: ENC[AES256_GCM,data:/4D7vGtpwqnEkPvM6eu8xH4tKL8=,iv:qn9bQv7mMyiSzLnn/GbL62WOwFOp4+QuGzw/pDp+lRA=,tag:m7wDSgL45Sae2CGa/6Olgg==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:AWOJPjapR1o=,iv:slld/IVpEiHJ5se7MfPPECP38EUEW9JJ5rLDJ3biDhk=,tag:JdTi2UseQCGy50vY+Xvutw==,type:str]
            admin-password: ENC[AES256_GCM,data:pnLHPEEm4NI=,iv:ZwLd4CO4aQfUGcYuUhyI8NQ3VDDXtL6Iq0Q5l3PT6pY=,tag:XdMgCv9XTJFvSe3tTlUh0g==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcDhJUHJzcmVqQUFIMjBY
            cllzYndLdm5RN3VoeVZLTkttanRyWTIvMVFvCjR5Ujd0WWNyZEIvMGFlZThleW5r
            VUZLaktzWU1NZmNMRzUzZy9Jd2FlbUUKLS0tIENjckV2K3drdENCZVYyVzFpS1pH
            Wm80TzdWZ2xhK2dGNk5CeGpqT1R2VDQKwcsEiA4D3Qpyq9Gapj0kFNdOFhSBTwwV
            XUW+LcogAI9NFT4U5yFk+zX5BQo7YKm2v3C1YCDlvM72LBrfVlRGtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T16:25:49Z"
    mac: ENC[AES256_GCM,data:kNebJs1rCTv1x7HcnXIzv4cUhhwh4d/qIQGqibQvkWxHJ5M8pdkHWYYhjLZAnwXwqqXLoan4IY1aDpPHjDs6KCQinEq+YxewtwRXk54fUqibrOAnJN1RXkSBAAcm5gfwoOd7ddBvI16YxGOA61j6G5FVULWZP3t5Plvl9FknSe8=,iv:NkjshRPAKdZg17J77Q0BMR4V9relLnuZMEBr96fr1Bc=,tag:K0SDDEVtINcton29ZhkZkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
