secrets:
    data:
        - name: ENC[AES256_GCM,data:jCrsgvD8LRQ7X/BUZp7UrkZHkWA=,iv:RRgMvLLA5ExnhtIFFEEeEupfqQ9W4D9Dr7EcokDtBhQ=,tag:+pUROO9QwxVCyGzLhmIPLw==,type:str]
          data:
            admin-user: ENC[AES256_GCM,data:o+9AuKeWTk4=,iv:jhuTZ65SWEcSe5GjgAbAxdHwX7UDAvHbpOhnAVw/AT8=,tag:+tWEtEHx6NqVs8rg7MCLbg==,type:str]
            admin-password: ENC[AES256_GCM,data:4f/obISAiqE=,iv:VvT2qfOObeHTI3nW3RN2mOf6HOs+uaoMwS/ztpZ6Gww=,tag:PVGuJPC1/a+P70NSP4fBxw==,type:str]
global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:rbBWMQ==,iv:QkPiN8ByVOdqGqJ2SWdzzeYDcBo1FxRv5KgvQoZKe+o=,tag:H0e6NCwyqvQNCvypqV9xLw==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:vfheaQ==,iv:BbcZb2SMyQM69lGwDh9f1qHqhAxzeNaExtY0Mbbv8N8=,tag:gA7Lu+VEASvY6e0a3LyBIA==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQUxwNTd3bFNKS2R0cS9p
            NHFGK2JvV29leXUwM3U0WTEwNmtaTjlCN3pNClJGbEUyVXhGNGVjMWJSaVgwS3d1
            eHEyQVBiVy9aN3paOHVSR3ExQmpsUm8KLS0tIFVNUjJ6Vi9rdUVNdnNXc0pQbjUv
            Rm9TVXRDMVJYQzRSZVpuNTZac0ZSTFkKovcVUZukkvQ/uxvJznn/LRbsAxOmyMYJ
            5o5r44X2EoSRWF2kmN5qS64/3YbvZcKyXEMLcIZewvqL6HXrrUKi6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-16T17:15:45Z"
    mac: ENC[AES256_GCM,data:QNYk+Ufn1QMkgUbRMQGnQo3JL1ph+Dw43IrXexw38ORitg/2vPncxPbsqXAxwZnTYIxsrS5Wl0j6tCBr6XraWuCMekFbMuiGoqkN3iOEBKhQss05X7XYdVu88rC0dgpSZvun6YvYzS0ZWN0xS5kak8q0PYvSPsf5XzKoilC3GJE=,iv:+gW/HbznrjsRSXjauw7/J0T/8oJT8W/OtTyhcmgoDME=,tag:J9kBwuN1Io6JhqCy9aschw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
