global:
    loki:
        basicAuthUsername: ENC[AES256_GCM,data:7yF4ZQ==,iv:Qg6Wx+Q11u5nTw0wTIcaV3evsp/CsJ/BP7+VsO3mkVs=,tag:AHipSuCb2IN6zSpTLcrJmg==,type:str]
        basicAuthPassword: ENC[AES256_GCM,data:0RyugA==,iv:68muACCRJZmm5W9a77nNpfPCotVdmalhRgEYByCxe0Q=,tag:qOHGhQugxwuhBg1+kbM5Bg==,type:str]
loki:
    gateway:
        basicAuth:
            #ENC[AES256_GCM,data:LclH1yNJ0p2O7ihDe32jwoiMbms4zahnZ9msqazB0soVeOXxmaqclLgN8VI2wVtsk7IHCzG6CG0SX2Z2pXQV0r884XxwmRuLz2w=,iv:rDffMy38sGzBfagPlYdDCD0M0Ut4rmGK1f0t4/9rVzQ=,tag:Hut6lP79X+JC8Qa3GhbmHA==,type:comment]
            username: ENC[AES256_GCM,data:WvuTsg==,iv:cRlLAJlPAuxCWvQ7aW0ilFnYi0zvspVejFHzuNITzSs=,tag:XHA0YBiolyeUOI4GCDBiCA==,type:str]
            password: ENC[AES256_GCM,data:zk8C/g==,iv:etgxceKy7YRid/Bf2/oglZLdhQLyGu238pj+KLokeUk=,tag:Id8Sy1OQ1bFJwuq5B3tjPA==,type:str]
sops:
    age:
        - recipient: age10s4608esauwjqgelw4g44euau02g5er3e5yecx4ex5gfcxdcdcms2xnrv3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYjdSdk92WVlKTW9TMFBy
            aSsrL2k5czZqaWRWenpoWHNETTJhd2k5am5NCnhKclBzNWloMjZVdkRnOG55M3Jq
            YkRTaFV0MWVFS1dNRW9IcUJFeWJubGsKLS0tIGxNcU9WM2d1dDJOYXF0Ky9jWGNV
            c2VaR3A2alFGTTVBV3pacTh5Z0s1a3cKr0TXJ0eCkkqLql4RJ4hehzfqcIlXzcws
            zdkoSPdd06yQnRn4EhO7j9YQvpThCB59ANgRPdvXYHDSfgYNL8K0AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T05:22:07Z"
    mac: ENC[AES256_GCM,data:10TD5Dhw6QriCyX73RpdhP79XgsbWcXgKS3OGFabJ55lzNpsyr9KsvmcTyrVPg+hKNzK2M+YiL8TGBm/RczRdI7OGauDt9LpUkSA5SiU9/gjOBRHcuBbxhKLBoI7+nr41MI8RzJOdICWZBSkJ6VuyZOc5VmdhsVGJgiN3jc1ht4=,iv:qh0x1WvrHtrMS+YCLpwZAI13jMlLiXUGbqTyFnksnZI=,tag:hb21PuxtiXt+UIF5TMjMUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
